name: DoubleSlider
author: frixxx
category: Interface
tags: [animation, slide, drag]
docs: http://js.frixxx.de.fx/projects/DoubleSlider/#documentation
demo: http://jsfiddle.net/t9Kpz/1/embedded/result/
current: 0.2
