name:  DoubleSlider
author:  Matthias Goebels
current:  0.1
category:  Interface
tags:  [animation,slide,drag]
docs:  http://moo.medienpark.net/DoubleSlider/docs.html
demo:  http://moo.medienpark.net/DoubleSlider/demo.html
